# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: main
            fetch-depth: 10
            submodules: true

      # Runs a single command using the runners shell
      - name: Make destination directory for compiled CSS
        run: mkdir -vp /css
        
      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.5
        with:
          source: scss/app.scss
          destination: css/style.css

      # Runs a set of commands using the runners shell
      - name: ssh deploy
        # You may pin to the exact commit or the version.
        # uses: easingthemes/ssh-deploy@c711f2c3391cac2876bf4c833590077f02e4bcb8
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          # Private Key
          SSH_PRIVATE_KEY: ${{ secrets.LONGVIEW }}
          # Remote host
          REMOTE_HOST: 188.127.237.150
          # Remote user
          REMOTE_USER: root
          # Remote port
          REMOTE_PORT: 22
          # Source directory
          SOURCE: ./*
          # Target directory
          TARGET: /home/admin/web/5tex.ru/public_html/longview
